gestureclean/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from . import views


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/vacs/')),
    url(r'^vacs/', include('vacs.urls')),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', views.user_login, name="login"),
    url(r'^accounts/logout/$',views.user_logout, name="logout"),
]

vacs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^experiments/$',
        views.experiment_list, name='experiment_list'),
    url(r'^experiments/new$',
        views.experiment_create, name='experiment_new'),
    url(r'^experiments/edit/(?P<pk>\d+)$',
        views.experiment_update, name='experiment_edit'),
    url(r'^delete/(?P<pk>\d+)$',
        views.experiment_delete, name='experiment_delete'),
    url(r'^experiments/(?P<e_pk>\d+)/evacs$',
        views.vac_list, name='vac_list'),
    url(r'^experiments/(?P<e_pk>\d+)/scores$',
        views.generate_scores, name='scores'),
    url(r'^experiments/(?P<e_pk>\d+)/evacs/new$',
        views.vac_create, name='vac_new'),
    url(r'^experiments/(?P<e_pk>\d+)/evacs/edit/(?P<pk>\d+)$',
        views.vac_update, name='vac_edit'),
    url(r'^experiments/(?P<e_pk>\d+)/evacs/delete/(?P<pk>\d+)$',
        views.vac_delete, name='vac_delete'),
    url(r'^assignments/(?P<a_pk>\d+)/evacs/(?P<v_pk>\d+)/evaluation/new$',
        views.evaluation_update, name='evaluation_edit'),
    url(r'^valassignments/(?P<a_pk>\d+)/scores/(?P<s_pk>\d+)/validation/new$',
        views.validation_update, name='validation_edit'),
    url(r'^validations/$',
        views.validation_index, name='validation_index'),
    url(r'^finished/$',
        views.finished, name='finished'),
]

vacs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.encoding import python_2_unicode_compatible
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete, post_save, post_delete
from django.contrib.auth.models import User
from django.db import models
from jsonfield import JSONField
from rolepermissions.roles import assign_role
from rolepermissions.checkers import has_role
import collections
import random, string
import json
from django.conf import settings
import yagmail


########################################
##############  GLOBALS  ###############
########################################
command_code = {
    1:2,
    2:2,
    3:2,
    4:2,
    5:4,
    6:4,
    7:2,
    8:2,
    9:2,
    10:4,
    11:2,
}

########################################
############## FUNCTIONS ###############
########################################
def randomword(length):
    return ''.join(random.choice(string.lowercase) for i in range(length))

def create_replication():
    random_groups = range(1,12)
    random.shuffle(random_groups)
    random_commands = []
    for index in random_groups:
        sub_commands = range(1,command_code[index]+1)
        random.shuffle(sub_commands)
        commands = [{ 'code': str(index) + '_'+str(sc), \
                      'pk': -1} for sc in sub_commands]
        random_commands.append(commands)
    return random_commands



########################################
##############  MODELS   ###############
########################################

class Experiment(models.Model):
    name = models.CharField(max_length=200)
    student_n = models.IntegerField(default=0,
            validators=[MinValueValidator(0)])
    expert_n = models.IntegerField(default=0,
            validators=[MinValueValidator(0)])
    student_cmd_n  = models.IntegerField(default=2,
            validators=[MinValueValidator(2)])
    expert_cmd_n  = models.IntegerField(default=1,
            validators=[MinValueValidator(1)])
    is_active = models.BooleanField(default=True)
    in_validation = models.BooleanField(default=False)
    replications = models.TextField(blank=True)
    val_replications = models.TextField(blank=True)
    owner = models.ForeignKey(User)

class Vac(models.Model):
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE, related_name='vacs')
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

class Participant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)

class Command(models.Model):
    name = models.CharField(unique=True, max_length=200)
    code = models.CharField(unique=True, max_length=4)

class Score(models.Model):
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    vac = models.ForeignKey(Vac, on_delete=models.CASCADE)
    command = models.ForeignKey(Command, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)
    lexicon_number = models.IntegerField(
            validators=[MinValueValidator(1),
	    MaxValueValidator(9)])


class Validation(models.Model):
    score = models.OneToOneField(
        Score,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    selected_lexicons = models.CharField(max_length=100, default='empty')
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

class Assignment(models.Model):
    command = models.ForeignKey(Command, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lexicon_order = models.CharField(max_length=200)
    current_comparison = models.IntegerField(default=0,
            validators=[MinValueValidator(0),
	    MaxValueValidator(15)])
    current_vac = models.ForeignKey(Vac,
	on_delete=models.CASCADE, null=True, blank=True,
        related_name='current_assigned')
    evaluated_vacs = models.ManyToManyField(Vac, blank=True,
            related_name='evaluated_assigned')
    done = models.BooleanField(default=False)

class ValAssignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    command = models.ForeignKey(Command, on_delete=models.CASCADE)
    lexicon_number = models.IntegerField(
        validators=[MinValueValidator(1),
        MaxValueValidator(9)])
    previous_validation = models.ForeignKey(Validation,
	on_delete=models.CASCADE, null=True, blank=True,
        related_name='previous_val_assigned')
    current_score = models.ForeignKey(Score,
	on_delete=models.CASCADE, null=True, blank=True,
        related_name='current_val_assigned')
    evaluated_scores = models.ManyToManyField(Score, blank=True,
            related_name='evaluated_val_assigned')
    current_color = models.IntegerField(default=0)
    done = models.BooleanField(default=False)

class Evaluation(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    vac = models.ForeignKey(Vac, on_delete=models.CASCADE)
    evaluation = models.CharField(default="empty", max_length=100)
    number = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    # unique_together = ("assignment","number","vac")



########################################
##############  SIGNALS  ###############
########################################
@receiver(post_save, sender=Experiment)
def model_post_save(sender, instance, created,**kwargs):
    if created:
	exp_key = instance.pk
	subj_count = 1
	user_list = []
	password_list = []
        print instance

	# Create students and experts
	for i in range(instance.expert_n):
	    username = 'e'+str(exp_key)+'_e'+str(i+1)
	    user = User.objects.create_user(
		    username=username,
		    email="example@example.com")
	    password = randomword(4)
	    user.set_password(password)
	    user.save()
	    new_user = User.objects.get(username=username)
	    assign_role(new_user, 'expert')
	    subj_count += 1
	    user_list.append(username)
	    password_list.append(password)
            participant = Participant(user=new_user, experiment=instance)
            participant.save()
	    print 'Expert {0} successfully created.'.format(username)
	    print 'Password: '+password

	for i in range(instance.student_n):
	    username = 'e'+str(exp_key)+'_s'+str(i+1)
	    user = User.objects.create_user(
		    username=username,
		    email="example@example.com")
	    password = randomword(4)
	    user.set_password(password)
            user.experiment = instance
	    user.save()
	    new_user = User.objects.get(username=username)
	    assign_role(new_user, 'student')
	    subj_count += 1
	    user_list.append(username)
	    password_list.append(password)
            participant = Participant(user=new_user, experiment=instance)
            participant.save()
	    print 'Student {0} successfully created.'.format(username)
	    print 'Password: '+password

	# Create The replications
	replications = [create_replication(),create_replication(),create_replication()]

	# Assign the gestures to the experts
	assigned = 0
	counter = 0
	replication = 0
	user_counter = 0
	total_assignments = instance.expert_n*instance.expert_cmd_n +\
			    instance.student_n*instance.student_cmd_n
        print "ASSIGNING USERS"
        print "Total assignments: ", total_assignments
	while (assigned <total_assignments):
	    user = User.objects.get(
		    username=user_list[user_counter])
	    if has_role(user,'expert'):
		command_n= instance.expert_cmd_n
	    else:
		command_n= instance.student_cmd_n
	    command_counter = 0
	    while(command_counter < command_n):
                print "assigned: " + str(assigned)
                print "user counter: " + str(user_counter)
                print "counter: " + str(counter)
                print "command_counter: " + str(command_counter)
                print "replications: " + str(replication)
                print "***************************************"
                print "***************************************"
		group_index = counter%11
		assignment_created = False
                full_code = replications[replication][group_index][0]['code']
                group_code = int(full_code.split('_')[0])
		for i in range(command_code[group_code]):
		    elem = replications[replication][group_index][i]
		    code = elem['code']
		    pk = elem['pk']
		    # If unassigned, assign it
		    if pk == -1:
                        lexicon_order = range(1,10)
                        random.shuffle(lexicon_order)
                        lexicon_order = ''.join([str(l)+',' for l in lexicon_order])
			command = Command.objects.get(code=code)
			assignment = Assignment.objects.create(
			    command = command,
                            lexicon_order = lexicon_order,
			    user = user)
			assignment.save()
			elem['pk'] = assignment.pk
			assigned += 1
                        command_counter +=1
                        replication = assigned/28
                        break
                counter += 1
	    user_counter += 1
        experiment = Experiment.objects.get(pk=instance.pk)
	experiment.replications = json.dumps(replications)
        print experiment.replications
        experiment.save()

        # Send email to the creator with all the data
        msg = "EXPERTS:\n"
        for index in range(instance.expert_n):
            msg += str(index+1)+") username: "+user_list[index]
            msg += ", password: "+password_list[index]+"\n"
        msg += "__________________________________\n"
        msg += "__________________________________\n"
        msg += "STUDENTS:\n"
        for index in range(instance.student_n):
            msg += str(index+1)+") username: "\

vacs/forms.py
from django import forms
from django.forms import ModelForm
from vacs.models import Experiment, Vac, Evaluation, Validation
from django.utils.translation import ugettext, ugettext_lazy as _
import re

class ExperimentForm(ModelForm):
    class Meta:
        model = Experiment
        fields = ('name','student_n','expert_n','student_cmd_n',
                'expert_cmd_n','is_active')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                     'id': 'inputName',
                                     'placeholder': 'Experiment Name'}),

            'student_n': forms.NumberInput(attrs={'class': 'form-control',
                                     'id': 'inputStudentN',
                                     'placeholder': 'Number of students'}),

            'expert_n': forms.NumberInput(attrs={'class': 'form-control',
                                     'id': 'inputExpertN',
                                     'placeholder': 'Number of Experts'}),

            'student_cmd_n': forms.NumberInput(attrs={'class': 'form-control',
                                     'id': 'inputStudentN',
                                     'placeholder': 'Number of commands per student'}),

            'expert_cmd_n': forms.NumberInput(attrs={'class': 'form-control',
                                     'id': 'inputExpertCmdN',
                                     'placeholder': 'Number of commands per expert'}),
        }

    def clean(self):
        cleaned_data = super(ExperimentForm, self).clean()
        s_n = cleaned_data.get("student_n")
        e_n = cleaned_data.get("expert_n")
        s_cmd_n = cleaned_data.get("student_cmd_n")
        e_cmd_n = cleaned_data.get("expert_cmd_n")
        command_number = s_n*s_cmd_n + e_n*e_cmd_n
        if command_number < 28:
            raise forms.ValidationError(
                "The total number of commands to be evaluated must be greater than 28"
            )
        elif command_number > 84:
            raise forms.ValidationError(
                "The total number of commands to be evaluated must be less than 85"
            )
        return self.cleaned_data



class VacForm(ModelForm):
    class Meta:
        model = Vac
        fields = ('name','description')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                     'id': 'inputName',
                                     'placeholder': 'VACs name'}),

            'description': forms.Textarea(attrs={'class': 'form-control',
                                     'id': 'inputDescription',
                                     'placeholder': 'VACs description'}),
        }

class EvaluationForm(ModelForm):
    class Meta:
        model = Evaluation
        fields = ('evaluation',)

    def clean(self):
        cleaned_data = super(EvaluationForm, self).clean()
        evaluation = cleaned_data.get("evaluation")
        match = re.search('^(([1-9]\.(=|<)\.[1-9]\.(=|<)\.[1-9])|empty)$',evaluation)
        if not match:
            raise forms.ValidationError(
                "Please make sure that you have one video in each of the boxes"
            )
        return self.cleaned_data


class ValidationForm(ModelForm):
    class Meta:
        model = Validation
        fields = ('selected_lexicons',)

    def clean(self):
        cleaned_data = super(ValidationForm, self).clean()
        selected_lexicons = cleaned_data.get("selected_lexicons")
        match = re.search('^(([1-9]\.)+|empty)$',selected_lexicons)
        if not match:
            raise forms.ValidationError(
                "Please make sure that you selected a video"
            )
        return self.cleaned_data

vacs/templates/vacs/base.html
<html lang="en">
    {% load static %}

    <!--HEAD-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">

        <title>GestureClean System</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/bootstrap.min.css' %}" />
        <!-- Bootstrap theme -->
        <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/bootstrap-theme.min.css' %}" />


        <!--My theme -->
        <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/theme.css' %}" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    </head>
    <!--END HEAD-->

    <!--BODy-->
    <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">GestureClean - ISAT Laboratory</a>
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right" style="position: relative; right: -200%;">
              <a class="navbar-brand pull-right" href="{% url 'logout' %}">Logout</a>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
      {% block content %}
      {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!--<script>window.jQuery || document.write('<script src="{% static 'vacs/styles/js/sdfjquery.min.js' %}"><\/script>')</script>-->
    <script src="{% static 'vacs/styles/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'vacs/styles/js/ie10-viewport-bug-workaround.js' %}"></script>

    </body>
</html>

vacs/templates/vacs/error_message.html
{% extends "vacs/base.html" %}
{% load widget_tweaks %}
{% block content %}

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
          <h1>{{ message }}</h1>
      </div>

    </div> <!-- /container -->
{% endblock %}

vacs/templates/vacs/evaluation_form.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GestureClean System</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/bootstrap.min.css' %}" />
    <!-- Bootstrap theme -->
    <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/bootstrap-theme.min.css' %}" />


    <!--My theme -->
    <link rel="stylesheet" type="text/css" href="{% static 'vacs/styles/css/theme.css' %}" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <style>
        #sortable0 {
            list-style-type: none;
            margin: 0; padding: 0;
            height: 240px;
        }
        #sortable1, #sortable2, #sortable3 {
            list-style-type: none;
            margin: 0; padding: 0;
            <!--width: 350px; height: 240px;-->
        }
        #sortable0 li {
            padding: 1px; float: left;
            text-align: center;
        }
    </style>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).on('click', '#submit_button', function (e) {
            console.log("ENTERED IN THE SUBMIT");
            var evaluation  = "";
            var left_symbol = $('input[name=comparator_left]:checked').val();
            var right_symbol = $('input[name=comparator_right]:checked').val();
            var symbol_list = ["."+left_symbol+".","."+right_symbol+".",""]
            var correct = true;
            for (i = 1; i < 4; i++) {
                var sortable = $('#sortable'+i+' > li');
                if (sortable.length == 0){
                    alert("Please put one video in each of the green boxes");
                    correct = true;
                    return false;
                } else {
                    evaluation += $('#sortable'+ i +' > li')[0].id;
                    evaluation += symbol_list[i-1]
                }
            }
            if (correct) {
                $('#id_evaluation').val(evaluation);
                $('#form_evaluation').submit();
            }
            return false;
        });
    </script>
    <script>
        $( function() {
        $( "#sortable0, ul" ).sortable({
          connectWith: ".connectedSortable",
            receive: function(event, ui) {
                var $this = $(this);
                if ($this.children('li').length > 1 && $this.attr('id') != "sortable0") {
                    console.log('Only one per list!');
                    $(ui.sender).sortable('cancel');
                }
            }
        }).disableSelection();
        } );
    </script>
</head>
<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">GestureClean - ISAT Laboratory</a>
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right" style="position: relative; right: -200%;">
              <a class="navbar-brand pull-right" href="{% url 'logout' %}">Logout</a>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

    <div class="row">
        <div class="col-md-1">
            <strong> Progress: </strong>
        </div>
        <div class="progress col-md-11">
            <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"><span class="sr-only">{{ progress }}% Complete</span></div>
        </div>
    </div>
    <div class="row">
    <div class="col-md-1"> </div>
    <div class="col-md-10">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">{{command.name}}</h3>
        </div>
        <div class="panel-body">
            <ul id="sortable0" class="connectedSortable">
                {% for subject in subjects %}
                {% with subject|stringformat:"s" as s %}
                    {% with "vacs/media/S"|add:subject|add:"/"|add:command.code|add:".webm" as video_path %}
                    <li id="{{ s }}"  class="ui-state-default">
                            <video width="300" height="225" controls loop preload="auto">
                                <source src="{% static video_path %}"
                                type="video/mp4"> Your browser does not support the video player, use Chrome or Firefox.
                            </video>
                        </li>
                    {% endwith %}
                {% endwith %}
                {% endfor %}
            </ul>
        </div>
    </div>
    </div>
    <div class="col-md-1"> </div>
    </div>
    <h1 class ="text-center">Order by: {{ vac.name }}</h1>
    <div class="row">
        <button type="button" class="btn btn-lg btn-primary vac-lbtn-group">LOW</button>
        <button type="button" class="btn btn-lg btn-danger vac-btn-group">HIGH</button>
    </div>

    <div class="row">
    <div style="position:relative;">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <ul id="sortable1" class="connectedSortable">
                    </ul>
                </div>
            </div>
        </div>

        <div class="well comparator1">
        <form>
          <input type="radio" name="comparator_left" value="<" checked> &lt less than<br>
          <input type="radio" name="comparator_left" value="="> = equal<br>
        </form>
        </div>

        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <ul id="sortable2" class="connectedSortable">
                    </ul>
                </div>
            </div>
        </div>

        <div class="well comparator2">
        <form>
          <input type="radio" name="comparator_right" value="<" checked> &lt less than<br>
          <input type="radio" name="comparator_right" value="="> = equal<br>
        </form>
        </div>


        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <ul id="sortable3" class="connectedSortable">
                    </ul>
                </div>
            </div>
        </div>

    </div>
    </div>



     <form id="form_evaluation" method="post">{% csrf_token %}
        <div class="vac-hidden">
            {{ form.as_p }}
        </div>
        <button id="submit_button" class="btn btn-primary btn-block" type="button">Submit</button>
    </form>

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors%}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    {% endif %}


    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!--<script>window.jQuery || document.write('<script src="{% static 'vacs/styles/js/sdfjquery.min.js' %}"><\/script>')</script>-->
    <script src="{% static 'vacs/styles/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="{% static 'vacs/styles/js/ie10-viewport-bug-workaround.js' %}"></script>-->
</body>
</html>

vacs/templates/vacs/experiment-list.html
{% extends "vacs/base.html" %}
{% load widget_tweaks %}
{% block content %}

<h1>Experiments</h1>
<ul>
    {% for experiment in object_list %}
    <li>{{ server.name }}:
    <a href="{% url "experiment-edit" experiment.id %}">edit</a>
    <a href="{% url "experiment-delete" experiment.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url "server_new" %}">New</a>
{% endblock %}

vacs/templates/vacs/experiment_confirm_delete.html
{% extends "vacs/base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="jumbotron">
    <p>Are you sure you want to delete the experiment: "{{ object.name }}" ?
    </p>
<form method="post" >{% csrf_token %}
    <button class="btn btn-danger" type="submit">Delete</button>
</form>
</div>
{% endblock %}

vacs/templates/vacs/experiment_list.html
{% extends "vacs/base.html" %}
{% load widget_tweaks %}
{% block content %}

<h1>Experiments</h1>

<div class="btn-group">
    <a href="{% url "experiment_new" %}" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
         Create Experiment
    </a>
</div>

<br>
<br>

<div class="col-md-8">
{% for experiment in object_list %}
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">{{ experiment.name }}</h3>
    </div>
    <div class="panel-body">
        <div class="col-md-2">
            <strong>Experts: </strong>
        </div>
        <div class="col-md-10">
            <p>{{experiment.expert_n}} experts, {{experiment.expert_cmd_n}} command(s) per expert</p>
        </div>

        <div class="col-md-2">
            <strong>Students: </strong>
        </div>
        <div class="col-md-10">
            <p>{{experiment.student_n}} students, {{experiment.student_cmd_n}} command(s) per student</p>
        </div>

        <div class="col-md-2">
            <strong>Active: </strong>
        </div>
        <div class="col-md-10"><p>
        {% if experiment.is_active %}
            Yes
        {% else %}
            No
        {% endif %}
        </p></div>


        {% if experiment.in_validation %}
        <div class="col-md-12"><p>
            <h5 class="text-primary"> In Validation Phase </h5>
        </div>
        {% endif %}

        <div class="btn-group col-md-9">
            <a href="{% url "vac_list" experiment.id %}" class="btn btn-sm btn-success">VACs</a>
            <a href="{% url "scores" experiment.id %}" class="btn btn-sm btn-info">Validation</a>
        </div>
        <div class="btn-group vac-btn-group col-md-3">
            <a href="{% url "experiment_edit" experiment.id %}" class="btn btn-sm btn-default">Edit</a>
            <a href="{% url "experiment_delete" experiment.id %}" class="btn btn-sm btn-danger">Delete</a>
        </div>
    </div>
</div>
{% endfor %}
</div>

{% endblock %}